apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-productpage
  namespace: student2-bookinfo-dev
  labels:
    app: bookinfo-dev-productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-productpage
  template:
    metadata:
      labels:
        app: bookinfo-dev-productpage
    spec:
      containers:
      - name: bookinfo-dev-productpage
        image: ghcr.io/chanayus/bookinfo-productpage:dev
        imagePullPolicy: Always
        env:
        - name: RATINGS_HOSTNAME
          value: 'itkmitl.bookinfo.dev.opsta.net/ratings'
        - name: DETAILS_HOSTNAME
          value: 'itkmitl.bookinfo.dev.opsta.net/details'
        - name: REVIEWS_HOSTNAME
          value: 'itkmitl.bookinfo.dev.opsta.net/reviews'
      imagePullSecrets:
      - name: registry-bookinfo